<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace eBayEnterprise\RetailOrderManagement\Payload\Payment;
use eBayEnterprise\RetailOrderManagement\Payload\ISerializable;

/**
 * 3D Secure Verification data
 *
 * Interface ISecureVerificationData
 * @package eBayEnterprise\RetailOrderManagement\Payload\Payment
 */
interface ISecureVerificationData extends ISerializable
{
    /**
     * Verified by VISA (VPAS) e-commerce transactions only.
     * Verify Enrollment Response from the VERes message, returned to the POE from the ACS server
     * as a result of a Verify Enrollment Request
     *
     * For all other transactions, enter spaces.
     *
     * 'Y' - Card eligible for authentication processing
     * 'N' - Attempted authentication. Card eligible for attempts liability,
     *       but attempts proof is not available from Issuer.
     * 'U' - Unable to process or card not eligible for attempts.
     *
     * @return string
     */
    function getAuthenticationAvailable();
    /**
     * Verified by VISA (VPAS) / MasterCard Secure Code (UCAF)
     * Transaction Status: For e-commerce VISA and MasterCard transactions only.
     * Returned in the PARes message from the ACS server in the “Transaction Status” field.
     *
     * For all other transactions, enter spaces.
     *
     * 'Y' - Authentication Approved
     * 'A' - Authentication attempted.
     * 'U' - Unable to authenticate (due to technical problems or excluded card type).
     * 'N' - Authentication failed.
     *
     * @return string
     */
    function getAuthenticationStatus();
    /**
     * E-commerce Verified by VISA and MasterCard SecureCode transactions only.
     * Data returned in authentication request.
     * For VISA, this field contains CAVV values in upacked, displayable format (0-9, A-F).
     * For MasterCard, this field contains the UCAF data in upacked,
     * displayable base-64 format (A-Z, a-z, 0-9, +, /, -).
     * Left justify, space-fill right.
     *
     * @return string
     */
    function getCavvUcaf();
    /**
     * E-commerce Verified by VISA transactions only.
     * XID data returned from authentication request in upacked, displayable format (0-9, AF).
     * Left justify, space-fill right.
     *
     * @return string
     */
    function getTransactionId();
    /**
     * @return string
     */
    function getECI();
    /**
     * The Issuer Bank ACS (Access Control Server) authenticates the cardholder.
     * The authentication result is represented by the Payer Authentication Response (PARes)
     * generated by the Card Issuer ACS.
     *
     * @return string
     */
    function getPayerAuthenticationResponse();
}
